### ISSUE TITLE
FAILED - RETRYING: yum install (3 retries left)- yum install

### ISSUE THREAD

**Issue by pavan257** [alvistack/ansible-role-bitbucket#3]
I am getting this error on amazon linux 2 version to install 8.6.1 version

TASK [alvistack.bitbucket : yum install] ***************************************
FAILED - RETRYING: yum install (3 retries left).
FAILED - RETRYING: yum install (2 retries left).
FAILED - RETRYING: yum install (1 retries left).
failed: [127.0.0.1] (item={'state': 'present', 'name': 'atlassian-bitbucket-100:8.6.1*'}) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "changes": {"installed": ["atlassian-bitbucket-100:8.6.1*"]}, "item": {"name": "atlassian-bitbucket-100:8.6.1*", "state": "present"}, "msg": "RPM needs to be updated\n", "rc": 1, "results": ["Loaded plugins: extras_suggestions,langpacks, priorities, update-motd\n541 packages excluded due to repository priority protections\nResolving Dependencies\n--> Running transaction check\n---> Package atlassian-bitbucket.x86_64 100:8.6.1-5.16 will be installed\n--> Processing Dependency: chrpath for package: 100:atlassian-bitbucket-8.6.1-5.16.x86_64\n--> Running transaction check\n---> Package chrpath.x86_64 0:0.16-0.amzn2.0.2 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package                Arch      Version Repository         Size\n================================================================================\nInstalling:\n atlassian-bitbucket    x86_64    100:8.6.1-5.16        home_alvistack     13 k\nInstalling for dependencies:\n chrpath                x86_64    0.16-0.amzn2.0.2      amzn2-core         26 k\n\nTransaction Summary\n================================================================================\nInstall  1 Package (+1 Dependent package)\n\nTotal size: 39 k\nInstalled size: 64 k\nDownloading packages:\nRunning transaction check\nERROR You need to update rpm to handle:\nrpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by atlassian-bitbucket-100:8.6.1-5.16.x86_64\n You could try running: rpm -Va --nofiles --nodigest\nYour transaction was saved, rerun it with:\n yum load-transaction /tmp/yum_save_tx.2022-12-14.07-36.Lwh2Sq.yumtx\n"]}

can we have parameter to provide lock_timeout  for yum lock freed?

**Comment by hswong3i** [comment]
For rpm based OS this Ansible Role currently supporting (see https://github.com/alvistack/ansible-role-bitbucket#requirements):

> Requirements
> 
> This role require Ansible community package 4.10 or higher.
> 
> This role was designed for:
> 
>     Ubuntu 18.04, 20.04, 22.04, 22.10
>     CentOS 7, 8 Stream, 9 Stream
>     openSUSE Leap 15.4, Tumbleweed
>     Debian 10, 11, Testing
>     Fedora 36, 37, Rawhide
>     RHEL 7, 8, 9

The rpm is build with OBS and could find from here: https://build.opensuse.org/package/show/home:alvistack/atlassian-atlassian-bitbucket-8.6.1.

The .spec file could find from here: https://github.com/alvistack/atlassian-atlassian-bitbucket/blob/alvistack/8.6.1/atlassian-bitbucket.spec. Actually it is just a wrapper for downloading official .tar.gz + patch + create uid/gid + systemd script. 

BTW, I have no idea about cross supporting Amazon Linux 2, although they may looks similar :-S
